name: norm

on: 
  push:

jobs:
  norm:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: Install Norminette
      run: |
        python3 -m pip install --upgrade pip setuptools
        python3 -m pip install norminette
    - name: norminette
      run: |
        norminette -v
        norminette incs srcs maps solong_main.c